FACE_LANDMARKER_MODEL_PATH = "models/face_landmarker.task"

ANTI_SPOOF_MODEL_PATH = "models/best_model.onnx"

ANTI_SPOOF_THRESHOLD = 0.65

EAR_THRESHOLD = 0.22

HEAD_TURN_THRESHOLD = 35

RANDOM_CHALLENGE_COUNT = 3

CHALLENGE_TIMEOUT_SECONDS = 8